---



version: "3.3"
services:
  app:
    build: ./app
    container_name: backend
    restart: unless-stopped
    environment:
      DATABASE_URI: postgresql://postgres:123@db:5432
    volumes:
      - for_download:/for_download
    networks:
      - external
      - internal
    depends_on:
      - db

  db:
    build: ./postgres
    container_name: postgres
    restart: unless-stopped
    networks:
      - internal
    environment:
      DB_USER: db_user
      DB_USER_PASSWORD: qwerty
      POSTGRES_DB: app
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  for_download:

networks:
  external:
  internal:
